// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACI498AcL5GtI0av4fO1QA9Hz3OpV4Iy8',
    appId: '1:798911300988:web:46eedcd001da3fcd88d0f9',
    messagingSenderId: '798911300988',
    projectId: 'recycle-d8b0d',
    authDomain: 'recycle-d8b0d.firebaseapp.com',
    storageBucket: 'recycle-d8b0d.firebasestorage.app',
    measurementId: 'G-FT0G6R298Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUzZ5ZCQtWfp9i7VhzEzrDuH6Gw_hQibU',
    appId: '1:798911300988:android:63fdc03ccdf8b14e88d0f9',
    messagingSenderId: '798911300988',
    projectId: 'recycle-d8b0d',
    storageBucket: 'recycle-d8b0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnxkwxg1NzAtXUa5-KaR03yFRb6UwtU9s',
    appId: '1:798911300988:ios:377a0d67b239846588d0f9',
    messagingSenderId: '798911300988',
    projectId: 'recycle-d8b0d',
    storageBucket: 'recycle-d8b0d.firebasestorage.app',
    iosBundleId: 'com.example.recycle',
  );
}
